#!/bin/sh

workdir=/usr/local/bin/logger

start() {
    cd $workdir
    /usr/bin/python logger.py &
    echo "logger.py started."
}

status() {
    pid_status=$(ps aux | grep logger.py | grep -v grep)
    echo $pid_status
}

stop() {
    pid=$(ps aux | grep logger.py | grep -v grep | awk '{print $2}')
    kill $pid
    sleep 2
    echo "logger.py killed."
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: /etc/init.d/logger {start|stop|restart|status}"
    exit 1
esac
exit 0
